# Generated by Django 2.2.9 on 2022-10-19 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20221018_2204'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='discription',
            new_name='description',
        ),
    ]
